version: '3.8'

services:
  invantry_db:
    image: mysql:latest
    container_name: invantry_db
    environment:
      MYSQL_ROOT_PASSWORD: secret_root_password
      MYSQL_DATABASE: invantry_db
      MYSQL_USER: invantry_user
      MYSQL_PASSWORD: secure_user_password
    ports:
      - "3307:3306"
    volumes:
      - invantry_mysql_data:/var/lib/mysql

  invantry_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: invantry_phpmyadmin
    environment:
      PMA_HOST: invantry_db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - invantry_db

volumes:
  invantry_mysql_data:

